/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard.projects'
import { Route as DashboardSlugRouteImport } from './routes/dashboard.$slug'
import { Route as AdminSlugRouteImport } from './routes/admin.$slug'
import { Route as DashboardSlugBugsRouteImport } from './routes/dashboard.$slug.bugs'
import { Route as DashboardSlugAnalyticsRouteImport } from './routes/dashboard.$slug.analytics'
import { Route as ApiWishVoteRouteImport } from './routes/api/wish/vote'
import { Route as ApiWishListRouteImport } from './routes/api/wish/list'
import { Route as ApiWishCreateRouteImport } from './routes/api/wish/create'
import { Route as ApiUserUpdateRouteImport } from './routes/api/user/update'
import { Route as ApiCommentCreateRouteImport } from './routes/api/comment/create'
import { Route as ApiBugScreenshotRouteImport } from './routes/api/bug/screenshot'
import { Route as ApiBugListRouteImport } from './routes/api/bug/list'
import { Route as ApiBugCreateRouteImport } from './routes/api/bug/create'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAdminProjectsRouteImport } from './routes/api/admin/projects'
import { Route as ApiAuthPasskeyIndexRouteImport } from './routes/api/auth/passkey/index'
import { Route as ApiAuthPasskeySummaryRouteImport } from './routes/api/auth/passkey/summary'
import { Route as ApiAuthPasskeyCredentialIdRouteImport } from './routes/api/auth/passkey/$credentialId'
import { Route as ApiAdminProjectsBootstrapRouteImport } from './routes/api/admin/projects/bootstrap'
import { Route as ApiAdminProjectsSlugRouteImport } from './routes/api/admin/projects/$slug'
import { Route as ApiAuthPasskeyRegisterVerifyRouteImport } from './routes/api/auth/passkey/register/verify'
import { Route as ApiAuthPasskeyRegisterOptionsRouteImport } from './routes/api/auth/passkey/register/options'
import { Route as ApiAuthPasskeyLoginVerifyRouteImport } from './routes/api/auth/passkey/login/verify'
import { Route as ApiAuthPasskeyLoginOptionsRouteImport } from './routes/api/auth/passkey/login/options'
import { Route as ApiAdminProjectsSlugTestEmailRouteImport } from './routes/api/admin/projects/$slug/test-email'
import { Route as ApiAdminProjectsSlugSettingsRouteImport } from './routes/api/admin/projects/$slug/settings'
import { Route as ApiAdminProjectsSlugBugsRouteImport } from './routes/api/admin/projects/$slug/bugs'
import { Route as ApiAdminProjectsSlugAnalyticsRouteImport } from './routes/api/admin/projects/$slug/analytics'
import { Route as ApiAdminProjectsSlugWishesWishIdRouteImport } from './routes/api/admin/projects/$slug/wishes/$wishId'
import { Route as ApiAdminProjectsSlugBugsBugIdRouteImport } from './routes/api/admin/projects/$slug/bugs/$bugId'
import { Route as ApiAdminProjectsSlugWishesWishIdMergeRouteImport } from './routes/api/admin/projects/$slug/wishes/$wishId/merge'
import { Route as ApiAdminProjectsSlugWishesWishIdCommentsRouteImport } from './routes/api/admin/projects/$slug/wishes/$wishId/comments'
import { Route as ApiAdminProjectsSlugBugsBugIdCommentsRouteImport } from './routes/api/admin/projects/$slug/bugs/$bugId/comments'
import { Route as ApiAdminProjectsSlugBugsBugIdScreenshotsKeyRouteImport } from './routes/api/admin/projects/$slug/bugs/$bugId/screenshots/$key'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSlugRoute = DashboardSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminSlugRoute = AdminSlugRouteImport.update({
  id: '/admin/$slug',
  path: '/admin/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSlugBugsRoute = DashboardSlugBugsRouteImport.update({
  id: '/bugs',
  path: '/bugs',
  getParentRoute: () => DashboardSlugRoute,
} as any)
const DashboardSlugAnalyticsRoute = DashboardSlugAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardSlugRoute,
} as any)
const ApiWishVoteRoute = ApiWishVoteRouteImport.update({
  id: '/api/wish/vote',
  path: '/api/wish/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWishListRoute = ApiWishListRouteImport.update({
  id: '/api/wish/list',
  path: '/api/wish/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWishCreateRoute = ApiWishCreateRouteImport.update({
  id: '/api/wish/create',
  path: '/api/wish/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserUpdateRoute = ApiUserUpdateRouteImport.update({
  id: '/api/user/update',
  path: '/api/user/update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommentCreateRoute = ApiCommentCreateRouteImport.update({
  id: '/api/comment/create',
  path: '/api/comment/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBugScreenshotRoute = ApiBugScreenshotRouteImport.update({
  id: '/api/bug/screenshot',
  path: '/api/bug/screenshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBugListRoute = ApiBugListRouteImport.update({
  id: '/api/bug/list',
  path: '/api/bug/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBugCreateRoute = ApiBugCreateRouteImport.update({
  id: '/api/bug/create',
  path: '/api/bug/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminProjectsRoute = ApiAdminProjectsRouteImport.update({
  id: '/api/admin/projects',
  path: '/api/admin/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthPasskeyIndexRoute = ApiAuthPasskeyIndexRouteImport.update({
  id: '/api/auth/passkey/',
  path: '/api/auth/passkey/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthPasskeySummaryRoute = ApiAuthPasskeySummaryRouteImport.update({
  id: '/api/auth/passkey/summary',
  path: '/api/auth/passkey/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthPasskeyCredentialIdRoute =
  ApiAuthPasskeyCredentialIdRouteImport.update({
    id: '/api/auth/passkey/$credentialId',
    path: '/api/auth/passkey/$credentialId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminProjectsBootstrapRoute =
  ApiAdminProjectsBootstrapRouteImport.update({
    id: '/bootstrap',
    path: '/bootstrap',
    getParentRoute: () => ApiAdminProjectsRoute,
  } as any)
const ApiAdminProjectsSlugRoute = ApiAdminProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiAdminProjectsRoute,
} as any)
const ApiAuthPasskeyRegisterVerifyRoute =
  ApiAuthPasskeyRegisterVerifyRouteImport.update({
    id: '/api/auth/passkey/register/verify',
    path: '/api/auth/passkey/register/verify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthPasskeyRegisterOptionsRoute =
  ApiAuthPasskeyRegisterOptionsRouteImport.update({
    id: '/api/auth/passkey/register/options',
    path: '/api/auth/passkey/register/options',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthPasskeyLoginVerifyRoute =
  ApiAuthPasskeyLoginVerifyRouteImport.update({
    id: '/api/auth/passkey/login/verify',
    path: '/api/auth/passkey/login/verify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthPasskeyLoginOptionsRoute =
  ApiAuthPasskeyLoginOptionsRouteImport.update({
    id: '/api/auth/passkey/login/options',
    path: '/api/auth/passkey/login/options',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminProjectsSlugTestEmailRoute =
  ApiAdminProjectsSlugTestEmailRouteImport.update({
    id: '/test-email',
    path: '/test-email',
    getParentRoute: () => ApiAdminProjectsSlugRoute,
  } as any)
const ApiAdminProjectsSlugSettingsRoute =
  ApiAdminProjectsSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ApiAdminProjectsSlugRoute,
  } as any)
const ApiAdminProjectsSlugBugsRoute =
  ApiAdminProjectsSlugBugsRouteImport.update({
    id: '/bugs',
    path: '/bugs',
    getParentRoute: () => ApiAdminProjectsSlugRoute,
  } as any)
const ApiAdminProjectsSlugAnalyticsRoute =
  ApiAdminProjectsSlugAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => ApiAdminProjectsSlugRoute,
  } as any)
const ApiAdminProjectsSlugWishesWishIdRoute =
  ApiAdminProjectsSlugWishesWishIdRouteImport.update({
    id: '/wishes/$wishId',
    path: '/wishes/$wishId',
    getParentRoute: () => ApiAdminProjectsSlugRoute,
  } as any)
const ApiAdminProjectsSlugBugsBugIdRoute =
  ApiAdminProjectsSlugBugsBugIdRouteImport.update({
    id: '/$bugId',
    path: '/$bugId',
    getParentRoute: () => ApiAdminProjectsSlugBugsRoute,
  } as any)
const ApiAdminProjectsSlugWishesWishIdMergeRoute =
  ApiAdminProjectsSlugWishesWishIdMergeRouteImport.update({
    id: '/merge',
    path: '/merge',
    getParentRoute: () => ApiAdminProjectsSlugWishesWishIdRoute,
  } as any)
const ApiAdminProjectsSlugWishesWishIdCommentsRoute =
  ApiAdminProjectsSlugWishesWishIdCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => ApiAdminProjectsSlugWishesWishIdRoute,
  } as any)
const ApiAdminProjectsSlugBugsBugIdCommentsRoute =
  ApiAdminProjectsSlugBugsBugIdCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => ApiAdminProjectsSlugBugsBugIdRoute,
  } as any)
const ApiAdminProjectsSlugBugsBugIdScreenshotsKeyRoute =
  ApiAdminProjectsSlugBugsBugIdScreenshotsKeyRouteImport.update({
    id: '/screenshots/$key',
    path: '/screenshots/$key',
    getParentRoute: () => ApiAdminProjectsSlugBugsBugIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/admin/$slug': typeof AdminSlugRoute
  '/dashboard/$slug': typeof DashboardSlugRouteWithChildren
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/api/admin/projects': typeof ApiAdminProjectsRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/bug/create': typeof ApiBugCreateRoute
  '/api/bug/list': typeof ApiBugListRoute
  '/api/bug/screenshot': typeof ApiBugScreenshotRoute
  '/api/comment/create': typeof ApiCommentCreateRoute
  '/api/user/update': typeof ApiUserUpdateRoute
  '/api/wish/create': typeof ApiWishCreateRoute
  '/api/wish/list': typeof ApiWishListRoute
  '/api/wish/vote': typeof ApiWishVoteRoute
  '/dashboard/$slug/analytics': typeof DashboardSlugAnalyticsRoute
  '/dashboard/$slug/bugs': typeof DashboardSlugBugsRoute
  '/api/admin/projects/$slug': typeof ApiAdminProjectsSlugRouteWithChildren
  '/api/admin/projects/bootstrap': typeof ApiAdminProjectsBootstrapRoute
  '/api/auth/passkey/$credentialId': typeof ApiAuthPasskeyCredentialIdRoute
  '/api/auth/passkey/summary': typeof ApiAuthPasskeySummaryRoute
  '/api/auth/passkey/': typeof ApiAuthPasskeyIndexRoute
  '/api/admin/projects/$slug/analytics': typeof ApiAdminProjectsSlugAnalyticsRoute
  '/api/admin/projects/$slug/bugs': typeof ApiAdminProjectsSlugBugsRouteWithChildren
  '/api/admin/projects/$slug/settings': typeof ApiAdminProjectsSlugSettingsRoute
  '/api/admin/projects/$slug/test-email': typeof ApiAdminProjectsSlugTestEmailRoute
  '/api/auth/passkey/login/options': typeof ApiAuthPasskeyLoginOptionsRoute
  '/api/auth/passkey/login/verify': typeof ApiAuthPasskeyLoginVerifyRoute
  '/api/auth/passkey/register/options': typeof ApiAuthPasskeyRegisterOptionsRoute
  '/api/auth/passkey/register/verify': typeof ApiAuthPasskeyRegisterVerifyRoute
  '/api/admin/projects/$slug/bugs/$bugId': typeof ApiAdminProjectsSlugBugsBugIdRouteWithChildren
  '/api/admin/projects/$slug/wishes/$wishId': typeof ApiAdminProjectsSlugWishesWishIdRouteWithChildren
  '/api/admin/projects/$slug/bugs/$bugId/comments': typeof ApiAdminProjectsSlugBugsBugIdCommentsRoute
  '/api/admin/projects/$slug/wishes/$wishId/comments': typeof ApiAdminProjectsSlugWishesWishIdCommentsRoute
  '/api/admin/projects/$slug/wishes/$wishId/merge': typeof ApiAdminProjectsSlugWishesWishIdMergeRoute
  '/api/admin/projects/$slug/bugs/$bugId/screenshots/$key': typeof ApiAdminProjectsSlugBugsBugIdScreenshotsKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/admin/$slug': typeof AdminSlugRoute
  '/dashboard/$slug': typeof DashboardSlugRouteWithChildren
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/api/admin/projects': typeof ApiAdminProjectsRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/bug/create': typeof ApiBugCreateRoute
  '/api/bug/list': typeof ApiBugListRoute
  '/api/bug/screenshot': typeof ApiBugScreenshotRoute
  '/api/comment/create': typeof ApiCommentCreateRoute
  '/api/user/update': typeof ApiUserUpdateRoute
  '/api/wish/create': typeof ApiWishCreateRoute
  '/api/wish/list': typeof ApiWishListRoute
  '/api/wish/vote': typeof ApiWishVoteRoute
  '/dashboard/$slug/analytics': typeof DashboardSlugAnalyticsRoute
  '/dashboard/$slug/bugs': typeof DashboardSlugBugsRoute
  '/api/admin/projects/$slug': typeof ApiAdminProjectsSlugRouteWithChildren
  '/api/admin/projects/bootstrap': typeof ApiAdminProjectsBootstrapRoute
  '/api/auth/passkey/$credentialId': typeof ApiAuthPasskeyCredentialIdRoute
  '/api/auth/passkey/summary': typeof ApiAuthPasskeySummaryRoute
  '/api/auth/passkey': typeof ApiAuthPasskeyIndexRoute
  '/api/admin/projects/$slug/analytics': typeof ApiAdminProjectsSlugAnalyticsRoute
  '/api/admin/projects/$slug/bugs': typeof ApiAdminProjectsSlugBugsRouteWithChildren
  '/api/admin/projects/$slug/settings': typeof ApiAdminProjectsSlugSettingsRoute
  '/api/admin/projects/$slug/test-email': typeof ApiAdminProjectsSlugTestEmailRoute
  '/api/auth/passkey/login/options': typeof ApiAuthPasskeyLoginOptionsRoute
  '/api/auth/passkey/login/verify': typeof ApiAuthPasskeyLoginVerifyRoute
  '/api/auth/passkey/register/options': typeof ApiAuthPasskeyRegisterOptionsRoute
  '/api/auth/passkey/register/verify': typeof ApiAuthPasskeyRegisterVerifyRoute
  '/api/admin/projects/$slug/bugs/$bugId': typeof ApiAdminProjectsSlugBugsBugIdRouteWithChildren
  '/api/admin/projects/$slug/wishes/$wishId': typeof ApiAdminProjectsSlugWishesWishIdRouteWithChildren
  '/api/admin/projects/$slug/bugs/$bugId/comments': typeof ApiAdminProjectsSlugBugsBugIdCommentsRoute
  '/api/admin/projects/$slug/wishes/$wishId/comments': typeof ApiAdminProjectsSlugWishesWishIdCommentsRoute
  '/api/admin/projects/$slug/wishes/$wishId/merge': typeof ApiAdminProjectsSlugWishesWishIdMergeRoute
  '/api/admin/projects/$slug/bugs/$bugId/screenshots/$key': typeof ApiAdminProjectsSlugBugsBugIdScreenshotsKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/admin/$slug': typeof AdminSlugRoute
  '/dashboard/$slug': typeof DashboardSlugRouteWithChildren
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/api/admin/projects': typeof ApiAdminProjectsRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/bug/create': typeof ApiBugCreateRoute
  '/api/bug/list': typeof ApiBugListRoute
  '/api/bug/screenshot': typeof ApiBugScreenshotRoute
  '/api/comment/create': typeof ApiCommentCreateRoute
  '/api/user/update': typeof ApiUserUpdateRoute
  '/api/wish/create': typeof ApiWishCreateRoute
  '/api/wish/list': typeof ApiWishListRoute
  '/api/wish/vote': typeof ApiWishVoteRoute
  '/dashboard/$slug/analytics': typeof DashboardSlugAnalyticsRoute
  '/dashboard/$slug/bugs': typeof DashboardSlugBugsRoute
  '/api/admin/projects/$slug': typeof ApiAdminProjectsSlugRouteWithChildren
  '/api/admin/projects/bootstrap': typeof ApiAdminProjectsBootstrapRoute
  '/api/auth/passkey/$credentialId': typeof ApiAuthPasskeyCredentialIdRoute
  '/api/auth/passkey/summary': typeof ApiAuthPasskeySummaryRoute
  '/api/auth/passkey/': typeof ApiAuthPasskeyIndexRoute
  '/api/admin/projects/$slug/analytics': typeof ApiAdminProjectsSlugAnalyticsRoute
  '/api/admin/projects/$slug/bugs': typeof ApiAdminProjectsSlugBugsRouteWithChildren
  '/api/admin/projects/$slug/settings': typeof ApiAdminProjectsSlugSettingsRoute
  '/api/admin/projects/$slug/test-email': typeof ApiAdminProjectsSlugTestEmailRoute
  '/api/auth/passkey/login/options': typeof ApiAuthPasskeyLoginOptionsRoute
  '/api/auth/passkey/login/verify': typeof ApiAuthPasskeyLoginVerifyRoute
  '/api/auth/passkey/register/options': typeof ApiAuthPasskeyRegisterOptionsRoute
  '/api/auth/passkey/register/verify': typeof ApiAuthPasskeyRegisterVerifyRoute
  '/api/admin/projects/$slug/bugs/$bugId': typeof ApiAdminProjectsSlugBugsBugIdRouteWithChildren
  '/api/admin/projects/$slug/wishes/$wishId': typeof ApiAdminProjectsSlugWishesWishIdRouteWithChildren
  '/api/admin/projects/$slug/bugs/$bugId/comments': typeof ApiAdminProjectsSlugBugsBugIdCommentsRoute
  '/api/admin/projects/$slug/wishes/$wishId/comments': typeof ApiAdminProjectsSlugWishesWishIdCommentsRoute
  '/api/admin/projects/$slug/wishes/$wishId/merge': typeof ApiAdminProjectsSlugWishesWishIdMergeRoute
  '/api/admin/projects/$slug/bugs/$bugId/screenshots/$key': typeof ApiAdminProjectsSlugBugsBugIdScreenshotsKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/health'
    | '/login'
    | '/admin/$slug'
    | '/dashboard/$slug'
    | '/dashboard/projects'
    | '/api/admin/projects'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/bug/create'
    | '/api/bug/list'
    | '/api/bug/screenshot'
    | '/api/comment/create'
    | '/api/user/update'
    | '/api/wish/create'
    | '/api/wish/list'
    | '/api/wish/vote'
    | '/dashboard/$slug/analytics'
    | '/dashboard/$slug/bugs'
    | '/api/admin/projects/$slug'
    | '/api/admin/projects/bootstrap'
    | '/api/auth/passkey/$credentialId'
    | '/api/auth/passkey/summary'
    | '/api/auth/passkey/'
    | '/api/admin/projects/$slug/analytics'
    | '/api/admin/projects/$slug/bugs'
    | '/api/admin/projects/$slug/settings'
    | '/api/admin/projects/$slug/test-email'
    | '/api/auth/passkey/login/options'
    | '/api/auth/passkey/login/verify'
    | '/api/auth/passkey/register/options'
    | '/api/auth/passkey/register/verify'
    | '/api/admin/projects/$slug/bugs/$bugId'
    | '/api/admin/projects/$slug/wishes/$wishId'
    | '/api/admin/projects/$slug/bugs/$bugId/comments'
    | '/api/admin/projects/$slug/wishes/$wishId/comments'
    | '/api/admin/projects/$slug/wishes/$wishId/merge'
    | '/api/admin/projects/$slug/bugs/$bugId/screenshots/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/health'
    | '/login'
    | '/admin/$slug'
    | '/dashboard/$slug'
    | '/dashboard/projects'
    | '/api/admin/projects'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/bug/create'
    | '/api/bug/list'
    | '/api/bug/screenshot'
    | '/api/comment/create'
    | '/api/user/update'
    | '/api/wish/create'
    | '/api/wish/list'
    | '/api/wish/vote'
    | '/dashboard/$slug/analytics'
    | '/dashboard/$slug/bugs'
    | '/api/admin/projects/$slug'
    | '/api/admin/projects/bootstrap'
    | '/api/auth/passkey/$credentialId'
    | '/api/auth/passkey/summary'
    | '/api/auth/passkey'
    | '/api/admin/projects/$slug/analytics'
    | '/api/admin/projects/$slug/bugs'
    | '/api/admin/projects/$slug/settings'
    | '/api/admin/projects/$slug/test-email'
    | '/api/auth/passkey/login/options'
    | '/api/auth/passkey/login/verify'
    | '/api/auth/passkey/register/options'
    | '/api/auth/passkey/register/verify'
    | '/api/admin/projects/$slug/bugs/$bugId'
    | '/api/admin/projects/$slug/wishes/$wishId'
    | '/api/admin/projects/$slug/bugs/$bugId/comments'
    | '/api/admin/projects/$slug/wishes/$wishId/comments'
    | '/api/admin/projects/$slug/wishes/$wishId/merge'
    | '/api/admin/projects/$slug/bugs/$bugId/screenshots/$key'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/health'
    | '/login'
    | '/admin/$slug'
    | '/dashboard/$slug'
    | '/dashboard/projects'
    | '/api/admin/projects'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/bug/create'
    | '/api/bug/list'
    | '/api/bug/screenshot'
    | '/api/comment/create'
    | '/api/user/update'
    | '/api/wish/create'
    | '/api/wish/list'
    | '/api/wish/vote'
    | '/dashboard/$slug/analytics'
    | '/dashboard/$slug/bugs'
    | '/api/admin/projects/$slug'
    | '/api/admin/projects/bootstrap'
    | '/api/auth/passkey/$credentialId'
    | '/api/auth/passkey/summary'
    | '/api/auth/passkey/'
    | '/api/admin/projects/$slug/analytics'
    | '/api/admin/projects/$slug/bugs'
    | '/api/admin/projects/$slug/settings'
    | '/api/admin/projects/$slug/test-email'
    | '/api/auth/passkey/login/options'
    | '/api/auth/passkey/login/verify'
    | '/api/auth/passkey/register/options'
    | '/api/auth/passkey/register/verify'
    | '/api/admin/projects/$slug/bugs/$bugId'
    | '/api/admin/projects/$slug/wishes/$wishId'
    | '/api/admin/projects/$slug/bugs/$bugId/comments'
    | '/api/admin/projects/$slug/wishes/$wishId/comments'
    | '/api/admin/projects/$slug/wishes/$wishId/merge'
    | '/api/admin/projects/$slug/bugs/$bugId/screenshots/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  AdminSlugRoute: typeof AdminSlugRoute
  ApiAdminProjectsRoute: typeof ApiAdminProjectsRouteWithChildren
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiBugCreateRoute: typeof ApiBugCreateRoute
  ApiBugListRoute: typeof ApiBugListRoute
  ApiBugScreenshotRoute: typeof ApiBugScreenshotRoute
  ApiCommentCreateRoute: typeof ApiCommentCreateRoute
  ApiUserUpdateRoute: typeof ApiUserUpdateRoute
  ApiWishCreateRoute: typeof ApiWishCreateRoute
  ApiWishListRoute: typeof ApiWishListRoute
  ApiWishVoteRoute: typeof ApiWishVoteRoute
  ApiAuthPasskeyCredentialIdRoute: typeof ApiAuthPasskeyCredentialIdRoute
  ApiAuthPasskeySummaryRoute: typeof ApiAuthPasskeySummaryRoute
  ApiAuthPasskeyIndexRoute: typeof ApiAuthPasskeyIndexRoute
  ApiAuthPasskeyLoginOptionsRoute: typeof ApiAuthPasskeyLoginOptionsRoute
  ApiAuthPasskeyLoginVerifyRoute: typeof ApiAuthPasskeyLoginVerifyRoute
  ApiAuthPasskeyRegisterOptionsRoute: typeof ApiAuthPasskeyRegisterOptionsRoute
  ApiAuthPasskeyRegisterVerifyRoute: typeof ApiAuthPasskeyRegisterVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$slug': {
      id: '/dashboard/$slug'
      path: '/$slug'
      fullPath: '/dashboard/$slug'
      preLoaderRoute: typeof DashboardSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/$slug': {
      id: '/admin/$slug'
      path: '/admin/$slug'
      fullPath: '/admin/$slug'
      preLoaderRoute: typeof AdminSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$slug/bugs': {
      id: '/dashboard/$slug/bugs'
      path: '/bugs'
      fullPath: '/dashboard/$slug/bugs'
      preLoaderRoute: typeof DashboardSlugBugsRouteImport
      parentRoute: typeof DashboardSlugRoute
    }
    '/dashboard/$slug/analytics': {
      id: '/dashboard/$slug/analytics'
      path: '/analytics'
      fullPath: '/dashboard/$slug/analytics'
      preLoaderRoute: typeof DashboardSlugAnalyticsRouteImport
      parentRoute: typeof DashboardSlugRoute
    }
    '/api/wish/vote': {
      id: '/api/wish/vote'
      path: '/api/wish/vote'
      fullPath: '/api/wish/vote'
      preLoaderRoute: typeof ApiWishVoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wish/list': {
      id: '/api/wish/list'
      path: '/api/wish/list'
      fullPath: '/api/wish/list'
      preLoaderRoute: typeof ApiWishListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wish/create': {
      id: '/api/wish/create'
      path: '/api/wish/create'
      fullPath: '/api/wish/create'
      preLoaderRoute: typeof ApiWishCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/update': {
      id: '/api/user/update'
      path: '/api/user/update'
      fullPath: '/api/user/update'
      preLoaderRoute: typeof ApiUserUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comment/create': {
      id: '/api/comment/create'
      path: '/api/comment/create'
      fullPath: '/api/comment/create'
      preLoaderRoute: typeof ApiCommentCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bug/screenshot': {
      id: '/api/bug/screenshot'
      path: '/api/bug/screenshot'
      fullPath: '/api/bug/screenshot'
      preLoaderRoute: typeof ApiBugScreenshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bug/list': {
      id: '/api/bug/list'
      path: '/api/bug/list'
      fullPath: '/api/bug/list'
      preLoaderRoute: typeof ApiBugListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bug/create': {
      id: '/api/bug/create'
      path: '/api/bug/create'
      fullPath: '/api/bug/create'
      preLoaderRoute: typeof ApiBugCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/projects': {
      id: '/api/admin/projects'
      path: '/api/admin/projects'
      fullPath: '/api/admin/projects'
      preLoaderRoute: typeof ApiAdminProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/passkey/': {
      id: '/api/auth/passkey/'
      path: '/api/auth/passkey'
      fullPath: '/api/auth/passkey/'
      preLoaderRoute: typeof ApiAuthPasskeyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/passkey/summary': {
      id: '/api/auth/passkey/summary'
      path: '/api/auth/passkey/summary'
      fullPath: '/api/auth/passkey/summary'
      preLoaderRoute: typeof ApiAuthPasskeySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/passkey/$credentialId': {
      id: '/api/auth/passkey/$credentialId'
      path: '/api/auth/passkey/$credentialId'
      fullPath: '/api/auth/passkey/$credentialId'
      preLoaderRoute: typeof ApiAuthPasskeyCredentialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/projects/bootstrap': {
      id: '/api/admin/projects/bootstrap'
      path: '/bootstrap'
      fullPath: '/api/admin/projects/bootstrap'
      preLoaderRoute: typeof ApiAdminProjectsBootstrapRouteImport
      parentRoute: typeof ApiAdminProjectsRoute
    }
    '/api/admin/projects/$slug': {
      id: '/api/admin/projects/$slug'
      path: '/$slug'
      fullPath: '/api/admin/projects/$slug'
      preLoaderRoute: typeof ApiAdminProjectsSlugRouteImport
      parentRoute: typeof ApiAdminProjectsRoute
    }
    '/api/auth/passkey/register/verify': {
      id: '/api/auth/passkey/register/verify'
      path: '/api/auth/passkey/register/verify'
      fullPath: '/api/auth/passkey/register/verify'
      preLoaderRoute: typeof ApiAuthPasskeyRegisterVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/passkey/register/options': {
      id: '/api/auth/passkey/register/options'
      path: '/api/auth/passkey/register/options'
      fullPath: '/api/auth/passkey/register/options'
      preLoaderRoute: typeof ApiAuthPasskeyRegisterOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/passkey/login/verify': {
      id: '/api/auth/passkey/login/verify'
      path: '/api/auth/passkey/login/verify'
      fullPath: '/api/auth/passkey/login/verify'
      preLoaderRoute: typeof ApiAuthPasskeyLoginVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/passkey/login/options': {
      id: '/api/auth/passkey/login/options'
      path: '/api/auth/passkey/login/options'
      fullPath: '/api/auth/passkey/login/options'
      preLoaderRoute: typeof ApiAuthPasskeyLoginOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/projects/$slug/test-email': {
      id: '/api/admin/projects/$slug/test-email'
      path: '/test-email'
      fullPath: '/api/admin/projects/$slug/test-email'
      preLoaderRoute: typeof ApiAdminProjectsSlugTestEmailRouteImport
      parentRoute: typeof ApiAdminProjectsSlugRoute
    }
    '/api/admin/projects/$slug/settings': {
      id: '/api/admin/projects/$slug/settings'
      path: '/settings'
      fullPath: '/api/admin/projects/$slug/settings'
      preLoaderRoute: typeof ApiAdminProjectsSlugSettingsRouteImport
      parentRoute: typeof ApiAdminProjectsSlugRoute
    }
    '/api/admin/projects/$slug/bugs': {
      id: '/api/admin/projects/$slug/bugs'
      path: '/bugs'
      fullPath: '/api/admin/projects/$slug/bugs'
      preLoaderRoute: typeof ApiAdminProjectsSlugBugsRouteImport
      parentRoute: typeof ApiAdminProjectsSlugRoute
    }
    '/api/admin/projects/$slug/analytics': {
      id: '/api/admin/projects/$slug/analytics'
      path: '/analytics'
      fullPath: '/api/admin/projects/$slug/analytics'
      preLoaderRoute: typeof ApiAdminProjectsSlugAnalyticsRouteImport
      parentRoute: typeof ApiAdminProjectsSlugRoute
    }
    '/api/admin/projects/$slug/wishes/$wishId': {
      id: '/api/admin/projects/$slug/wishes/$wishId'
      path: '/wishes/$wishId'
      fullPath: '/api/admin/projects/$slug/wishes/$wishId'
      preLoaderRoute: typeof ApiAdminProjectsSlugWishesWishIdRouteImport
      parentRoute: typeof ApiAdminProjectsSlugRoute
    }
    '/api/admin/projects/$slug/bugs/$bugId': {
      id: '/api/admin/projects/$slug/bugs/$bugId'
      path: '/$bugId'
      fullPath: '/api/admin/projects/$slug/bugs/$bugId'
      preLoaderRoute: typeof ApiAdminProjectsSlugBugsBugIdRouteImport
      parentRoute: typeof ApiAdminProjectsSlugBugsRoute
    }
    '/api/admin/projects/$slug/wishes/$wishId/merge': {
      id: '/api/admin/projects/$slug/wishes/$wishId/merge'
      path: '/merge'
      fullPath: '/api/admin/projects/$slug/wishes/$wishId/merge'
      preLoaderRoute: typeof ApiAdminProjectsSlugWishesWishIdMergeRouteImport
      parentRoute: typeof ApiAdminProjectsSlugWishesWishIdRoute
    }
    '/api/admin/projects/$slug/wishes/$wishId/comments': {
      id: '/api/admin/projects/$slug/wishes/$wishId/comments'
      path: '/comments'
      fullPath: '/api/admin/projects/$slug/wishes/$wishId/comments'
      preLoaderRoute: typeof ApiAdminProjectsSlugWishesWishIdCommentsRouteImport
      parentRoute: typeof ApiAdminProjectsSlugWishesWishIdRoute
    }
    '/api/admin/projects/$slug/bugs/$bugId/comments': {
      id: '/api/admin/projects/$slug/bugs/$bugId/comments'
      path: '/comments'
      fullPath: '/api/admin/projects/$slug/bugs/$bugId/comments'
      preLoaderRoute: typeof ApiAdminProjectsSlugBugsBugIdCommentsRouteImport
      parentRoute: typeof ApiAdminProjectsSlugBugsBugIdRoute
    }
    '/api/admin/projects/$slug/bugs/$bugId/screenshots/$key': {
      id: '/api/admin/projects/$slug/bugs/$bugId/screenshots/$key'
      path: '/screenshots/$key'
      fullPath: '/api/admin/projects/$slug/bugs/$bugId/screenshots/$key'
      preLoaderRoute: typeof ApiAdminProjectsSlugBugsBugIdScreenshotsKeyRouteImport
      parentRoute: typeof ApiAdminProjectsSlugBugsBugIdRoute
    }
  }
}

interface DashboardSlugRouteChildren {
  DashboardSlugAnalyticsRoute: typeof DashboardSlugAnalyticsRoute
  DashboardSlugBugsRoute: typeof DashboardSlugBugsRoute
}

const DashboardSlugRouteChildren: DashboardSlugRouteChildren = {
  DashboardSlugAnalyticsRoute: DashboardSlugAnalyticsRoute,
  DashboardSlugBugsRoute: DashboardSlugBugsRoute,
}

const DashboardSlugRouteWithChildren = DashboardSlugRoute._addFileChildren(
  DashboardSlugRouteChildren,
)

interface DashboardRouteChildren {
  DashboardSlugRoute: typeof DashboardSlugRouteWithChildren
  DashboardProjectsRoute: typeof DashboardProjectsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSlugRoute: DashboardSlugRouteWithChildren,
  DashboardProjectsRoute: DashboardProjectsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ApiAdminProjectsSlugBugsBugIdRouteChildren {
  ApiAdminProjectsSlugBugsBugIdCommentsRoute: typeof ApiAdminProjectsSlugBugsBugIdCommentsRoute
  ApiAdminProjectsSlugBugsBugIdScreenshotsKeyRoute: typeof ApiAdminProjectsSlugBugsBugIdScreenshotsKeyRoute
}

const ApiAdminProjectsSlugBugsBugIdRouteChildren: ApiAdminProjectsSlugBugsBugIdRouteChildren =
  {
    ApiAdminProjectsSlugBugsBugIdCommentsRoute:
      ApiAdminProjectsSlugBugsBugIdCommentsRoute,
    ApiAdminProjectsSlugBugsBugIdScreenshotsKeyRoute:
      ApiAdminProjectsSlugBugsBugIdScreenshotsKeyRoute,
  }

const ApiAdminProjectsSlugBugsBugIdRouteWithChildren =
  ApiAdminProjectsSlugBugsBugIdRoute._addFileChildren(
    ApiAdminProjectsSlugBugsBugIdRouteChildren,
  )

interface ApiAdminProjectsSlugBugsRouteChildren {
  ApiAdminProjectsSlugBugsBugIdRoute: typeof ApiAdminProjectsSlugBugsBugIdRouteWithChildren
}

const ApiAdminProjectsSlugBugsRouteChildren: ApiAdminProjectsSlugBugsRouteChildren =
  {
    ApiAdminProjectsSlugBugsBugIdRoute:
      ApiAdminProjectsSlugBugsBugIdRouteWithChildren,
  }

const ApiAdminProjectsSlugBugsRouteWithChildren =
  ApiAdminProjectsSlugBugsRoute._addFileChildren(
    ApiAdminProjectsSlugBugsRouteChildren,
  )

interface ApiAdminProjectsSlugWishesWishIdRouteChildren {
  ApiAdminProjectsSlugWishesWishIdCommentsRoute: typeof ApiAdminProjectsSlugWishesWishIdCommentsRoute
  ApiAdminProjectsSlugWishesWishIdMergeRoute: typeof ApiAdminProjectsSlugWishesWishIdMergeRoute
}

const ApiAdminProjectsSlugWishesWishIdRouteChildren: ApiAdminProjectsSlugWishesWishIdRouteChildren =
  {
    ApiAdminProjectsSlugWishesWishIdCommentsRoute:
      ApiAdminProjectsSlugWishesWishIdCommentsRoute,
    ApiAdminProjectsSlugWishesWishIdMergeRoute:
      ApiAdminProjectsSlugWishesWishIdMergeRoute,
  }

const ApiAdminProjectsSlugWishesWishIdRouteWithChildren =
  ApiAdminProjectsSlugWishesWishIdRoute._addFileChildren(
    ApiAdminProjectsSlugWishesWishIdRouteChildren,
  )

interface ApiAdminProjectsSlugRouteChildren {
  ApiAdminProjectsSlugAnalyticsRoute: typeof ApiAdminProjectsSlugAnalyticsRoute
  ApiAdminProjectsSlugBugsRoute: typeof ApiAdminProjectsSlugBugsRouteWithChildren
  ApiAdminProjectsSlugSettingsRoute: typeof ApiAdminProjectsSlugSettingsRoute
  ApiAdminProjectsSlugTestEmailRoute: typeof ApiAdminProjectsSlugTestEmailRoute
  ApiAdminProjectsSlugWishesWishIdRoute: typeof ApiAdminProjectsSlugWishesWishIdRouteWithChildren
}

const ApiAdminProjectsSlugRouteChildren: ApiAdminProjectsSlugRouteChildren = {
  ApiAdminProjectsSlugAnalyticsRoute: ApiAdminProjectsSlugAnalyticsRoute,
  ApiAdminProjectsSlugBugsRoute: ApiAdminProjectsSlugBugsRouteWithChildren,
  ApiAdminProjectsSlugSettingsRoute: ApiAdminProjectsSlugSettingsRoute,
  ApiAdminProjectsSlugTestEmailRoute: ApiAdminProjectsSlugTestEmailRoute,
  ApiAdminProjectsSlugWishesWishIdRoute:
    ApiAdminProjectsSlugWishesWishIdRouteWithChildren,
}

const ApiAdminProjectsSlugRouteWithChildren =
  ApiAdminProjectsSlugRoute._addFileChildren(ApiAdminProjectsSlugRouteChildren)

interface ApiAdminProjectsRouteChildren {
  ApiAdminProjectsSlugRoute: typeof ApiAdminProjectsSlugRouteWithChildren
  ApiAdminProjectsBootstrapRoute: typeof ApiAdminProjectsBootstrapRoute
}

const ApiAdminProjectsRouteChildren: ApiAdminProjectsRouteChildren = {
  ApiAdminProjectsSlugRoute: ApiAdminProjectsSlugRouteWithChildren,
  ApiAdminProjectsBootstrapRoute: ApiAdminProjectsBootstrapRoute,
}

const ApiAdminProjectsRouteWithChildren =
  ApiAdminProjectsRoute._addFileChildren(ApiAdminProjectsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  AdminSlugRoute: AdminSlugRoute,
  ApiAdminProjectsRoute: ApiAdminProjectsRouteWithChildren,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiBugCreateRoute: ApiBugCreateRoute,
  ApiBugListRoute: ApiBugListRoute,
  ApiBugScreenshotRoute: ApiBugScreenshotRoute,
  ApiCommentCreateRoute: ApiCommentCreateRoute,
  ApiUserUpdateRoute: ApiUserUpdateRoute,
  ApiWishCreateRoute: ApiWishCreateRoute,
  ApiWishListRoute: ApiWishListRoute,
  ApiWishVoteRoute: ApiWishVoteRoute,
  ApiAuthPasskeyCredentialIdRoute: ApiAuthPasskeyCredentialIdRoute,
  ApiAuthPasskeySummaryRoute: ApiAuthPasskeySummaryRoute,
  ApiAuthPasskeyIndexRoute: ApiAuthPasskeyIndexRoute,
  ApiAuthPasskeyLoginOptionsRoute: ApiAuthPasskeyLoginOptionsRoute,
  ApiAuthPasskeyLoginVerifyRoute: ApiAuthPasskeyLoginVerifyRoute,
  ApiAuthPasskeyRegisterOptionsRoute: ApiAuthPasskeyRegisterOptionsRoute,
  ApiAuthPasskeyRegisterVerifyRoute: ApiAuthPasskeyRegisterVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
